# image will be published to ghcr.io/<user>/<name>
name: fedora-blue-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.github.jeromerobert.pdfarranger
        - com.github.johnfactotum.Foliate
        - com.github.neithern.g4music
        - com.github.rafostar.Clapper
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.usebottles.bottles
        - com.vysp3r.ProtonPlus
        - dev.vencord.Vesktop
        - io.github.dvlv.boxbuddyrs
        - io.github.fabrialberio.pinapp
        - io.github.getnf.embellish
        - io.gitlab.adhami3310.Converter
        - io.gitlab.adhami3310.Footage
        - io.gitlab.theevilskeleton.Upscaler
        - it.mijorus.gearlever
        - me.iepure.devtoolbox
        - net.nokyan.Resources
        - org.gnome.FileRoller
        - org.gnome.Papers
        - org.gnome.World.PikaBackup
        - org.mozilla.firefox
        - org.onlyoffice.desktopeditors
        - page.kramo.Sly
        - re.sonny.Junction

      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

